# Generated by Django 5.2.4 on 2025-07-16 23:13

import socio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('solicitud_ingreso', models.FileField(upload_to=socio.models.solicitud_socio_upload_path, verbose_name='Solicitud de Ingreso')),
                ('designacion_beneficiario', models.FileField(upload_to=socio.models.solicitud_socio_upload_path, verbose_name='Designación de Beneficiario')),
                ('autorizacion_descuento', models.FileField(upload_to=socio.models.solicitud_socio_upload_path, verbose_name='Autorización de Descuento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=10)),
            ],
            options={
                'verbose_name': 'Solicitud de Socio',
                'verbose_name_plural': 'Solicitudes de Socios',
            },
        ),
    ]
